### ISSUE TITLE
A lambda implementation

### ISSUE THREAD

**Issue by ChengranAA** [bediger4000/python_cons_car_cdr#1]
```python
# combinators
K = lambda a: lambda b : a
KI = lambda a: lambda b: b

CONS = lambda a, b: lambda f: f(a, b)
CAR = lambda p: p(lambda a, b: K(a)(b)) 
CDR = lambda p: p(lambda a, b: KI(a)(b))
```

**Comment by bediger4000** [comment]
Looks too much like the dreaded Lambda Calculus (https://github.com/bediger4000/lambda-calculator)

Python is supposed to be executable pseudo-code, right? People who write pseudo-code are scared of lambda calculus
